import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'pa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'GULJAR HARDWARE',
    'app.subtitle': 'Inventory Management',
    'nav.inventory': 'Inventory',
    'nav.billing': 'Billing',
    'nav.history': 'Sales History',
    'stats.totalProducts': 'Total Products',
    'stats.unitsInStock': 'units in stock',
    'stats.inventoryValue': 'Inventory Value',
    'stats.totalStockValue': 'Total stock value',
    'stats.lowStockItems': 'Low Stock Items',
    'stats.needsAttention': 'Needs attention',
    'stats.allStocked': 'All stocked',
    'stats.cartTotal': 'Cart Total',
    'stats.itemsInCart': 'items in cart',
    'inventory.searchItems': 'Search items...',
    'inventory.addItem': 'Add Item',
    'inventory.itemName': 'Item Name',
    'inventory.sku': 'SKU',
    'inventory.hsn': 'HSN',
    'inventory.category': 'Category',
    'inventory.price': 'Price',
    'inventory.quantity': 'Quantity',
    'inventory.status': 'Status',
    'inventory.actions': 'Actions',
    'inventory.noMatch': 'No items match your search.',
    'inventory.noItems': 'No items in inventory. Add your first item!',
    'inventory.inStock': 'In Stock',
    'inventory.lowStock': 'Low Stock',
    'inventory.outOfStock': 'Out of Stock',
    'inventory.deleteItem': 'Delete Item',
    'inventory.deleteConfirm': 'Are you sure you want to delete',
    'inventory.deleteWarning': 'This action cannot be undone.',
    'inventory.cancel': 'Cancel',
    'inventory.delete': 'Delete',
    'form.editItem': 'Edit Item',
    'form.addNewItem': 'Add New Item',
    'form.itemNameLabel': 'Item Name',
    'form.skuLabel': 'SKU',
    'form.hsnLabel': 'HSN Code',
    'form.categoryLabel': 'Category',
    'form.priceLabel': 'Price (₹)',
    'form.quantityLabel': 'Quantity',
    'form.minStockLabel': 'Min Stock Alert',
    'form.cancel': 'Cancel',
    'form.saveChanges': 'Save Changes',
    'form.addItem': 'Add Item',
    'billing.selectProducts': 'Select Products',
    'billing.searchProducts': 'Search products...',
    'billing.noProductsMatch': 'No products match your search.',
    'billing.noProducts': 'No products available.',
    'billing.left': 'left',
    'billing.currentBill': 'Current Bill',
    'billing.customerName': 'Customer name (optional)',
    'billing.cartEmpty': 'Cart is empty',
    'billing.addProducts': 'Add products to create a bill',
    'billing.each': 'each',
    'billing.subtotal': 'Subtotal',
    'billing.total': 'Total',
    'billing.clear': 'Clear',
    'billing.completeSale': 'Complete Sale',
    'history.salesHistory': 'Sales History',
    'history.totalBills': 'Total Bills',
    'history.totalSales': 'Total Sales',
    'history.avgBillValue': 'Avg Bill Value',
    'history.searchBills': 'Search by bill ID, customer, or item...',
    'history.noBills': 'No sales recorded yet.',
    'history.noMatch': 'No bills match your search.',
    'history.item': 'item',
    'history.items': 'items',
    'history.view': 'View',
    'receipt.taxInvoice': 'Tax Invoice',
    'receipt.billReceipt': 'Bill Receipt',
    'receipt.invoiceReceipt': 'Invoice / Receipt',
    'receipt.billNo': 'Bill No',
    'receipt.date': 'Date',
    'receipt.customer': 'Customer',
    'receipt.sno': 'S.No',
    'receipt.particulars': 'Particulars',
    'receipt.item': 'Item',
    'receipt.qty': 'Qty',
    'receipt.rate': 'Rate',
    'receipt.amount': 'Amount',
    'receipt.grandTotal': 'Grand Total',
    'receipt.bankDetails': 'Bank Details',
    'receipt.forShop': 'For, GULJAR HARDWARE',
    'receipt.shopAddress': 'Main Road, New Bus Stand Chowk, DALLI-RAJHARA (C.G.) 491 228\nPh: 088780 69050, 075870 95288',
    'receipt.thankYou': 'Thank you for your purchase!',
    'receipt.close': 'Close',
    'receipt.print': 'Print',
    'toast.itemAdded': 'Item Added',
    'toast.itemAddedDesc': 'has been added to inventory.',
    'toast.itemUpdated': 'Item Updated',
    'toast.itemUpdatedDesc': 'Inventory item has been updated.',
    'toast.itemDeleted': 'Item Deleted',
    'toast.itemDeletedDesc': 'Item has been removed from inventory.',
    'toast.insufficientStock': 'Insufficient Stock',
    'toast.only': 'Only',
    'toast.unitsAvailable': 'units available.',
    'toast.emptyCart': 'Empty Cart',
    'toast.emptyCartDesc': 'Add items to cart before completing sale.',
    'toast.saleComplete': 'Sale Complete',
    'toast.billDeleted': 'Bill Deleted',
    'toast.billDeletedDesc': 'Bill has been removed from history.',
    'billing.customerGstin': 'Customer GSTIN (optional)',
    'billing.bankName': 'Bank Name',
    'billing.accountNo': 'Account No.',
    'billing.ifscCode': 'IFSC Code',
    'history.deleteBill': 'Delete Bill',
    'history.deleteConfirm': 'Are you sure you want to delete bill',
    'history.deleteWarning': 'This action cannot be undone.',
    'loading.inventory': 'Loading inventory...',
  },
  hi: {
    'app.title': 'गुलज़ार हार्डवेयर (GULJAR HARDWARE)',
    'app.subtitle': 'इन्वेंट्री प्रबंधन',
    'nav.inventory': 'इन्वेंट्री',
    'nav.billing': 'बिलिंग',
    'nav.history': 'बिक्री इतिहास',
    'stats.totalProducts': 'कुल उत्पाद',
    'stats.unitsInStock': 'इकाइयाँ स्टॉक में',
    'stats.inventoryValue': 'इन्वेंट्री मूल्य',
    'stats.totalStockValue': 'कुल स्टॉक मूल्य',
    'stats.lowStockItems': 'कम स्टॉक आइटम',
    'stats.needsAttention': 'ध्यान देने की जरूरत',
    'stats.allStocked': 'सब स्टॉक में',
    'stats.cartTotal': 'कार्ट कुल',
    'stats.itemsInCart': 'आइटम कार्ट में',
    'inventory.searchItems': 'आइटम खोजें...',
    'inventory.addItem': 'आइटम जोड़ें',
    'inventory.itemName': 'आइटम का नाम',
    'inventory.sku': 'एसकेयू',
    'inventory.hsn': 'एचएसएन',
    'inventory.category': 'श्रेणी',
    'inventory.price': 'कीमत',
    'inventory.quantity': 'मात्रा',
    'inventory.status': 'स्थिति',
    'inventory.actions': 'कार्रवाई',
    'inventory.noMatch': 'कोई आइटम आपकी खोज से मेल नहीं खाता।',
    'inventory.noItems': 'इन्वेंट्री में कोई आइटम नहीं है। अपना पहला आइटम जोड़ें!',
    'inventory.inStock': 'स्टॉक में',
    'inventory.lowStock': 'कम स्टॉक',
    'inventory.outOfStock': 'स्टॉक खत्म',
    'inventory.deleteItem': 'आइटम हटाएं',
    'inventory.deleteConfirm': 'क्या आप वाकई हटाना चाहते हैं',
    'inventory.deleteWarning': 'यह कार्रवाई पूर्ववत नहीं की जा सकती।',
    'inventory.cancel': 'रद्द करें',
    'inventory.delete': 'हटाएं',
    'form.editItem': 'आइटम संपादित करें',
    'form.addNewItem': 'नया आइटम जोड़ें',
    'form.itemNameLabel': 'आइटम का नाम',
    'form.skuLabel': 'एसकेयू',
    'form.hsnLabel': 'एचएसएन कोड',
    'form.categoryLabel': 'श्रेणी',
    'form.priceLabel': 'कीमत (₹)',
    'form.quantityLabel': 'मात्रा',
    'form.minStockLabel': 'न्यूनतम स्टॉक अलर्ट',
    'form.cancel': 'रद्द करें',
    'form.saveChanges': 'बदलाव सहेजें',
    'form.addItem': 'आइटम जोड़ें',
    'billing.selectProducts': 'उत्पाद चुनें',
    'billing.searchProducts': 'उत्पाद खोजें...',
    'billing.noProductsMatch': 'कोई उत्पाद आपकी खोज से मेल नहीं खाता।',
    'billing.noProducts': 'कोई उत्पाद उपलब्ध नहीं है।',
    'billing.left': 'बचे',
    'billing.currentBill': 'वर्तमान बिल',
    'billing.customerName': 'ग्राहक का नाम (वैकल्पिक)',
    'billing.cartEmpty': 'कार्ट खाली है',
    'billing.addProducts': 'बिल बनाने के लिए उत्पाद जोड़ें',
    'billing.each': 'प्रत्येक',
    'billing.subtotal': 'उप-योग',
    'billing.total': 'कुल',
    'billing.clear': 'साफ करें',
    'billing.completeSale': 'बिक्री पूर्ण करें',
    'history.salesHistory': 'बिक्री इतिहास',
    'history.totalBills': 'कुल बिल',
    'history.totalSales': 'कुल बिक्री',
    'history.avgBillValue': 'औसत बिल मूल्य',
    'history.searchBills': 'बिल नंबर, ग्राहक, या आइटम से खोजें...',
    'history.noBills': 'अभी तक कोई बिक्री नहीं हुई।',
    'history.noMatch': 'कोई बिल आपकी खोज से मेल नहीं खाता।',
    'history.item': 'आइटम',
    'history.items': 'आइटम',
    'history.view': 'देखें',
    'receipt.taxInvoice': 'कर चालान',
    'receipt.billReceipt': 'बिल रसीद',
    'receipt.invoiceReceipt': 'चालान / रसीद',
    'receipt.billNo': 'बिल नंबर',
    'receipt.date': 'तारीख',
    'receipt.customer': 'ग्राहक',
    'receipt.sno': 'क्र.सं.',
    'receipt.particulars': 'विवरण',
    'receipt.item': 'आइटम',
    'receipt.qty': 'मात्रा',
    'receipt.rate': 'दर',
    'receipt.amount': 'राशि',
    'receipt.grandTotal': 'कुल योग',
    'receipt.bankDetails': 'बैंक विवरण',
    'receipt.forShop': 'For, GULJAR HARDWARE',
    'receipt.shopAddress': 'Main Road, New Bus Stand Chowk, DALLI-RAJHARA (C.G.) 491 228\nPh: 088780 69050, 075870 95288',
    'receipt.thankYou': 'खरीदारी के लिए धन्यवाद!',
    'receipt.close': 'बंद करें',
    'receipt.print': 'प्रिंट करें',
    'toast.itemAdded': 'आइटम जोड़ा गया',
    'toast.itemAddedDesc': 'इन्वेंट्री में जोड़ा गया है।',
    'toast.itemUpdated': 'आइटम अपडेट किया गया',
    'toast.itemUpdatedDesc': 'इन्वेंट्री आइटम अपडेट किया गया है।',
    'toast.itemDeleted': 'आइटम हटाया गया',
    'toast.itemDeletedDesc': 'आइटम इन्वेंट्री से हटा दिया गया है।',
    'toast.insufficientStock': 'अपर्याप्त स्टॉक',
    'toast.only': 'केवल',
    'toast.unitsAvailable': 'इकाइयाँ उपलब्ध हैं।',
    'toast.emptyCart': 'कार्ट खाली है',
    'toast.emptyCartDesc': 'बिक्री पूर्ण करने से पहले कार्ट में आइटम जोड़ें।',
    'toast.saleComplete': 'बिक्री पूर्ण',
    'toast.billDeleted': 'बिल हटाया गया',
    'toast.billDeletedDesc': 'बिल इतिहास से हटा दिया गया है।',
    'billing.customerGstin': 'ग्राहक GSTIN (वैकल्पिक)',
    'billing.bankName': 'बैंक का नाम',
    'billing.accountNo': 'खाता नंबर',
    'billing.ifscCode': 'IFSC कोड',
    'history.deleteBill': 'बिल हटाएं',
    'history.deleteConfirm': 'क्या आप वाकई इस बिल को हटाना चाहते हैं',
    'history.deleteWarning': 'यह कार्रवाई पूर्ववत नहीं की जा सकती।',
    'loading.inventory': 'इन्वेंट्री लोड हो रही है...',
  },
  pa: {
    'app.title': 'ਗੁਲਜ਼ਾਰ ਹਾਰਡਵੇਅਰ (GULJAR HARDWARE)',
    'app.subtitle': 'ਇਨਵੈਂਟਰੀ ਪ੍ਰਬੰਧਨ',
    'nav.inventory': 'ਇਨਵੈਂਟਰੀ',
    'nav.billing': 'ਬਿਲਿੰਗ',
    'nav.history': 'ਵਿਕਰੀ ਇਤਿਹਾਸ',
    'stats.totalProducts': 'ਕੁੱਲ ਉਤਪਾਦ',
    'stats.unitsInStock': 'ਯੂਨਿਟ ਸਟਾਕ ਵਿੱਚ',
    'stats.inventoryValue': 'ਇਨਵੈਂਟਰੀ ਮੁੱਲ',
    'stats.totalStockValue': 'ਕੁੱਲ ਸਟਾਕ ਮੁੱਲ',
    'stats.lowStockItems': 'ਘੱਟ ਸਟਾਕ ਆਈਟਮ',
    'stats.needsAttention': 'ਧਿਆਨ ਦੀ ਲੋੜ',
    'stats.allStocked': 'ਸਭ ਸਟਾਕ ਵਿੱਚ',
    'stats.cartTotal': 'ਕਾਰਟ ਕੁੱਲ',
    'stats.itemsInCart': 'ਆਈਟਮ ਕਾਰਟ ਵਿੱਚ',
    'inventory.searchItems': 'ਆਈਟਮ ਖੋਜੋ...',
    'inventory.addItem': 'ਆਈਟਮ ਜੋੜੋ',
    'inventory.itemName': 'ਆਈਟਮ ਦਾ ਨਾਮ',
    'inventory.sku': 'ਐਸਕੇਯੂ',
    'inventory.hsn': 'ਐਚਐਸਐਨ',
    'inventory.category': 'ਸ਼੍ਰੇਣੀ',
    'inventory.price': 'ਕੀਮਤ',
    'inventory.quantity': 'ਮਾਤਰਾ',
    'inventory.status': 'ਸਥਿਤੀ',
    'inventory.actions': 'ਕਾਰਵਾਈ',
    'inventory.noMatch': 'ਕੋਈ ਆਈਟਮ ਤੁਹਾਡੀ ਖੋਜ ਨਾਲ ਮੇਲ ਨਹੀਂ ਖਾਂਦਾ।',
    'inventory.noItems': 'ਇਨਵੈਂਟਰੀ ਵਿੱਚ ਕੋਈ ਆਈਟਮ ਨਹੀਂ। ਆਪਣਾ ਪਹਿਲਾ ਆਈਟਮ ਜੋੜੋ!',
    'inventory.inStock': 'ਸਟਾਕ ਵਿੱਚ',
    'inventory.lowStock': 'ਘੱਟ ਸਟਾਕ',
    'inventory.outOfStock': 'ਸਟਾਕ ਖਤਮ',
    'inventory.deleteItem': 'ਆਈਟਮ ਮਿਟਾਓ',
    'inventory.deleteConfirm': 'ਕੀ ਤੁਸੀਂ ਸੱਚਮੁੱਚ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ',
    'inventory.deleteWarning': 'ਇਹ ਕਾਰਵਾਈ ਅਣਕੀਤੀ ਨਹੀਂ ਜਾ ਸਕਦੀ।',
    'inventory.cancel': 'ਰੱਦ ਕਰੋ',
    'inventory.delete': 'ਮਿਟਾਓ',
    'form.editItem': 'ਆਈਟਮ ਸੰਪਾਦਿਤ ਕਰੋ',
    'form.addNewItem': 'ਨਵਾਂ ਆਈਟਮ ਜੋੜੋ',
    'form.itemNameLabel': 'ਆਈਟਮ ਦਾ ਨਾਮ',
    'form.skuLabel': 'ਐਸਕੇਯੂ',
    'form.hsnLabel': 'ਐਚਐਸਐਨ ਕੋਡ',
    'form.categoryLabel': 'ਸ਼੍ਰੇਣੀ',
    'form.priceLabel': 'ਕੀਮਤ (₹)',
    'form.quantityLabel': 'ਮਾਤਰਾ',
    'form.minStockLabel': 'ਘੱਟੋ-ਘੱਟ ਸਟਾਕ ਚੇਤਾਵਨੀ',
    'form.cancel': 'ਰੱਦ ਕਰੋ',
    'form.saveChanges': 'ਬਦਲਾਅ ਸੁਰੱਖਿਅਤ ਕਰੋ',
    'form.addItem': 'ਆਈਟਮ ਜੋੜੋ',
    'billing.selectProducts': 'ਉਤਪਾਦ ਚੁਣੋ',
    'billing.searchProducts': 'ਉਤਪਾਦ ਖੋਜੋ...',
    'billing.noProductsMatch': 'ਕੋਈ ਉਤਪਾਦ ਤੁਹਾਡੀ ਖੋਜ ਨਾਲ ਮੇਲ ਨਹੀਂ ਖਾਂਦਾ।',
    'billing.noProducts': 'ਕੋਈ ਉਤਪਾਦ ਉਪਲਬਧ ਨਹੀਂ।',
    'billing.left': 'ਬਾਕੀ',
    'billing.currentBill': 'ਮੌਜੂਦਾ ਬਿੱਲ',
    'billing.customerName': 'ਗਾਹਕ ਦਾ ਨਾਮ (ਵਿਕਲਪਿਕ)',
    'billing.cartEmpty': 'ਕਾਰਟ ਖਾਲੀ ਹੈ',
    'billing.addProducts': 'ਬਿੱਲ ਬਣਾਉਣ ਲਈ ਉਤਪਾਦ ਜੋੜੋ',
    'billing.each': 'ਹਰੇਕ',
    'billing.subtotal': 'ਉਪ-ਕੁੱਲ',
    'billing.total': 'ਕੁੱਲ',
    'billing.clear': 'ਸਾਫ਼ ਕਰੋ',
    'billing.completeSale': 'ਵਿਕਰੀ ਪੂਰੀ ਕਰੋ',
    'history.salesHistory': 'ਵਿਕਰੀ ਇਤਿਹਾਸ',
    'history.totalBills': 'ਕੁੱਲ ਬਿੱਲ',
    'history.totalSales': 'ਕੁੱਲ ਵਿਕਰੀ',
    'history.avgBillValue': 'ਔਸਤ ਬਿੱਲ ਮੁੱਲ',
    'history.searchBills': 'ਬਿੱਲ ਨੰਬਰ, ਗਾਹਕ, ਜਾਂ ਆਈਟਮ ਨਾਲ ਖੋਜੋ...',
    'history.noBills': 'ਅਜੇ ਕੋਈ ਵਿਕਰੀ ਨਹੀਂ ਹੋਈ।',
    'history.noMatch': 'ਕੋਈ ਬਿੱਲ ਤੁਹਾਡੀ ਖੋਜ ਨਾਲ ਮੇਲ ਨਹੀਂ ਖਾਂਦਾ।',
    'history.item': 'ਆਈਟਮ',
    'history.items': 'ਆਈਟਮਾਂ',
    'history.view': 'ਦੇਖੋ',
    'receipt.taxInvoice': 'ਟੈਕਸ ਇਨਵੌਇਸ',
    'receipt.billReceipt': 'ਬਿੱਲ ਰਸੀਦ',
    'receipt.invoiceReceipt': 'ਇਨਵੌਇਸ / ਰਸੀਦ',
    'receipt.billNo': 'ਬਿੱਲ ਨੰਬਰ',
    'receipt.date': 'ਤਾਰੀਖ',
    'receipt.customer': 'ਗਾਹਕ',
    'receipt.sno': 'ਕ੍ਰ.ਸੰ.',
    'receipt.particulars': 'ਵੇਰਵੇ',
    'receipt.item': 'ਆਈਟਮ',
    'receipt.qty': 'ਮਾਤਰਾ',
    'receipt.rate': 'ਦਰ',
    'receipt.amount': 'ਰਕਮ',
    'receipt.grandTotal': 'ਕੁੱਲ ਜੋੜ',
    'receipt.bankDetails': 'ਬੈਂਕ ਵੇਰਵੇ',
    'receipt.forShop': 'For, GULJAR HARDWARE',
    'receipt.shopAddress': 'Main Road, New Bus Stand Chowk, DALLI-RAJHARA (C.G.) 491 228\nPh: 088780 69050, 075870 95288',
    'receipt.thankYou': 'ਤੁਹਾਡੀ ਖਰੀਦ ਲਈ ਧੰਨਵਾਦ!',
    'receipt.close': 'ਬੰਦ ਕਰੋ',
    'receipt.print': 'ਪ੍ਰਿੰਟ ਕਰੋ',
    'toast.itemAdded': 'ਆਈਟਮ ਜੋੜਿਆ ਗਿਆ',
    'toast.itemAddedDesc': 'ਇਨਵੈਂਟਰੀ ਵਿੱਚ ਜੋੜਿਆ ਗਿਆ ਹੈ।',
    'toast.itemUpdated': 'ਆਈਟਮ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ',
    'toast.itemUpdatedDesc': 'ਇਨਵੈਂਟਰੀ ਆਈਟਮ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ ਹੈ।',
    'toast.itemDeleted': 'ਆਈਟਮ ਮਿਟਾਇਆ ਗਿਆ',
    'toast.itemDeletedDesc': 'ਆਈਟਮ ਇਨਵੈਂਟਰੀ ਤੋਂ ਹਟਾ ਦਿੱਤਾ ਗਿਆ ਹੈ।',
    'toast.insufficientStock': 'ਨਾਕਾਫ਼ੀ ਸਟਾਕ',
    'toast.only': 'ਸਿਰਫ਼',
    'toast.unitsAvailable': 'ਯੂਨਿਟ ਉਪਲਬਧ ਹਨ।',
    'toast.emptyCart': 'ਕਾਰਟ ਖਾਲੀ ਹੈ',
    'toast.emptyCartDesc': 'ਵਿਕਰੀ ਪੂਰੀ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਕਾਰਟ ਵਿੱਚ ਆਈਟਮ ਜੋੜੋ।',
    'toast.saleComplete': 'ਵਿਕਰੀ ਪੂਰੀ',
    'toast.billDeleted': 'ਬਿੱਲ ਮਿਟਾਇਆ ਗਿਆ',
    'toast.billDeletedDesc': 'ਬਿੱਲ ਇਤਿਹਾਸ ਤੋਂ ਹਟਾ ਦਿੱਤਾ ਗਿਆ ਹੈ।',
    'billing.customerGstin': 'ਗਾਹਕ GSTIN (ਵਿਕਲਪਿਕ)',
    'billing.bankName': 'ਬੈਂਕ ਦਾ ਨਾਮ',
    'billing.accountNo': 'ਖਾਤਾ ਨੰਬਰ',
    'billing.ifscCode': 'IFSC ਕੋਡ',
    'history.deleteBill': 'ਬਿੱਲ ਮਿਟਾਓ',
    'history.deleteConfirm': 'ਕੀ ਤੁਸੀਂ ਸੱਚਮੁੱਚ ਇਹ ਬਿੱਲ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ',
    'history.deleteWarning': 'ਇਹ ਕਾਰਵਾਈ ਅਣਕੀਤੀ ਨਹੀਂ ਜਾ ਸਕਦੀ।',
    'loading.inventory': 'ਇਨਵੈਂਟਰੀ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
